import { MemgraphConnection, MemgraphConnectionInfo } from '../models/memgraph-connection';
import { IDatasetInfoContext } from '../models/dataset-info';
import { MemgraphSchema } from '../models/memgraph-schema';
import { IMemgraphStorageStatsOptions, MemgraphNodePropertyStats, MemgraphRelationshipPropertyStats, MemgraphStorageStats } from '../models/memgraph-stats';
import { CreateMemgraphStream, MemgraphDetailedStream, MemgraphStream, MemgraphStreamDryRunOptions, MemgraphStreamDryRunResult } from '../models/memgraph-stream';
import { CreateMemgraphModule, MemgraphModule, MemgraphModuleFunctionType, UpdateMemgraphModule } from '../models/memgraph-module';
import { ILabChangelogVersion } from '../models/lab-changelog';
import { MemgraphIndex } from '../models/memgraph-index';
import { MemgraphConstraint } from '../models/memgraph-constraint';
import { MemgraphQueryResult } from '../models/memgraph-query-result';
import { MemgraphWebSocketConnection } from '../../models/memgraph/ws-connection';
import { INotification } from '../models/notification';
import { MemgraphDatabase, MemgraphDatabaseChange } from '../models/memgraph-database';
import { IMemgraphTransaction, IMemgraphTransactionTerminate } from '../models/memgraph-transaction';
import { ILlmOllamaSetup, ILlmAzureVerificationRequest, ILlmOpenAIVerificationRequest, ILlmRequest, ILlmVerificationResponse, IMemgraphTextQueryResult } from '../models/llm';
export interface IMemgraphService {
    connectionInfo: MemgraphConnectionInfo | null;
    getWSConnection(): MemgraphWebSocketConnection;
    checkConnection(connectionConfig?: MemgraphConnection): Promise<boolean>;
    createConnection(connectionConfig?: MemgraphConnection): Promise<MemgraphConnectionInfo>;
    closeConnection(): Promise<void>;
    isConnected(): boolean;
    isConnectionActive(): Promise<boolean>;
    getDatasets(): Promise<IDatasetInfoContext>;
    getDataset(slug: string): Promise<any>;
    getDatasetContent(slug: string): Promise<string>;
    getSchema(): Promise<MemgraphSchema>;
    getStorageStats(options?: Partial<IMemgraphStorageStatsOptions>): Promise<MemgraphStorageStats>;
    getNodesPropertyStats(): Promise<MemgraphNodePropertyStats[]>;
    getRelationshipsPropertyStats(): Promise<MemgraphRelationshipPropertyStats[]>;
    getStreams(): Promise<MemgraphStream[]>;
    getStream(streamName: string): Promise<MemgraphDetailedStream>;
    createStream(stream: CreateMemgraphStream): Promise<MemgraphDetailedStream>;
    checkStream(streamName: string, options?: MemgraphStreamDryRunOptions): Promise<MemgraphStreamDryRunResult[]>;
    stopStream(streamName: string): Promise<void>;
    startStream(streamName: string): Promise<void>;
    removeStream(streamName: string): Promise<void>;
    getModule(moduleName: string): Promise<MemgraphModule>;
    getModules(functionType?: MemgraphModuleFunctionType): Promise<MemgraphModule[]>;
    createModule(module: CreateMemgraphModule): Promise<MemgraphModule>;
    updateModule(moduleName: string, module: UpdateMemgraphModule): Promise<MemgraphModule>;
    removeModule(moduleName: string): Promise<void>;
    getIndexes(): Promise<MemgraphIndex[]>;
    createIndex(index: MemgraphIndex): Promise<MemgraphIndex>;
    removeIndex(index: MemgraphIndex): Promise<void>;
    removeIndexes(): Promise<void>;
    getConstraints(): Promise<MemgraphConstraint[]>;
    createConstraint(constraint: MemgraphConstraint): Promise<MemgraphConstraint>;
    removeConstraint(constraint: MemgraphConstraint): Promise<void>;
    removeConstraints(): Promise<void>;
    runQuery(query: string, params?: Record<string, any>, metadata?: Record<string, any>): Promise<MemgraphQueryResult>;
    runTextQuery(llmRequest: ILlmRequest): Promise<IMemgraphTextQueryResult>;
    verifyOpenAISetup(credentials: ILlmOpenAIVerificationRequest): Promise<ILlmVerificationResponse>;
    verifyAzureOpenAISetup(credentials: ILlmAzureVerificationRequest): Promise<ILlmVerificationResponse>;
    verifyOllamaSetup(credentials: ILlmOllamaSetup): Promise<ILlmVerificationResponse>;
    getDatabases(): Promise<MemgraphDatabase[]>;
    useDatabase(databaseName: string): Promise<MemgraphDatabaseChange>;
    loadDatabase(queries: Array<string>): Promise<void>;
    dropDatabase(): Promise<void>;
    dumpDatabase(): any;
    getNotifications(sessionId: string): Promise<INotification[]>;
    markNotificationsAsSeen(sessionId: string): Promise<void>;
    getVersions(): Promise<ILabChangelogVersion[]>;
    getTransactions(): Promise<IMemgraphTransaction[]>;
    terminateTransaction(transactionId: string): Promise<IMemgraphTransactionTerminate>;
}
